= ntp-formula

https://travis-ci.com/saltstack-formulas/ntp-formula[image:https://travis-ci.com/saltstack-formulas/ntp-formula.svg?branch=master[Travis CI Build Status]]
https://github.com/semantic-release/semantic-release[image:https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic--release-e10079.svg[Semantic Release]]

Formula to set up and configure the ntp client or server.

== General notes

See the full
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html[SaltStack
Formulas installation and usage instructions].

If you are interested in writing or contributing to formulas, please pay
attention to the
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#writing-formulas[Writing
Formula Section].

If you want to use this formula, please pay attention to the `FORMULA`
file and/or `git tag`, which contains the currently released version.
This formula is versioned according to http://semver.org/[Semantic
Versioning].

See
https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#versioning[Formula
Versioning Section] for more details.

If you need (non-default) configuration, please pay attention to the
`pillar.example` file and/or link:#_special_notes[Special notes] section.

== Contributing to this repo

*Commit message formatting is significant!!*

Please see
xref:main::CONTRIBUTING.adoc[How
to contribute] for more details.

== Special notes

None

== Available states

=== `ntp`

Installs the ntp package, and optionally, a basic config.

=== `ntp.server`

Installs the ntp server, an optional server config, and starts the ntp
server.

=== `ntp.local_server`

This formula uses pillar data to determine if the server is an internal
NTP server or a local server that syncs to the internal NTP server and
will write the ntp.conf file accordingly.

Requires CentOS 5.X or CentOS 6.X.

=== `ntp.ng`

This state is a re-implementation of the original NTP formula. As a
state, `ntp.ng` controls both the client and server through pillar
parameters. This formula does not require that a configuration file be
served directly and instead fully exposes all ntp configuration
parameters as set in the pillar.

*Note:* `ntp.ng` relies upon some conventions first available in the
_Helium_ release.

== Testing

Linux testing is done with `kitchen-salt`.

=== Requirements

* Ruby
* Docker

[source,bash]
----
$ gem install bundler
$ bundle install
$ bin/kitchen test [platform]
----

Where `[platform]` is the platform name defined in `kitchen.yml`, e.g.
`debian-9-2019-2-py3`.

=== `bin/kitchen converge`

Creates the docker instance and runs the `template` main state, ready
for testing.

=== `bin/kitchen verify`

Runs the `inspec` tests on the actual instance.

=== `bin/kitchen destroy`

Removes the docker instance.

=== `bin/kitchen test`

Runs all of the stages above in one go: i.e. `destroy` + `converge` +
`verify` + `destroy`.

=== `bin/kitchen login`

Gives you SSH access to the instance for manual testing.
